permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "Brian's Try & Catch"
email: "brian90191@gmail.com"
author: "Brian Ye"
description: "先有 Try 才有 Catch<br/>記不下的就交給技術筆記吧"
github_username:  "brian90191"
facebook_username: "yiwei.yeah"

swiftype_searchId: "2Rgg95m4s99-q75zSfaX"
disqus_shortname: "brianye"
leancloud:
  enable: true
  app_id: Pnco3PgUc8i36FthevToeSGE-gzGzoHsz
  app_key: v4jtnwjdv32EgYKYM7Ak66sa



url: "https://brian90191.github.io/blog"
imgrepo: "https://brian90191.github.io/blog/static/img"


# url: "http://127.0.0.1:4000"
# imgrepo: "http://127.0.0.1:4000/static/img"


theme: jekyll-theme-cayman
